# Generated by Django 3.2.3 on 2022-03-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='year',
        ),
    ]
